name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows:
      - Site Index Page
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-deployment
  cancel-in-progress: false

jobs:

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: site  # Checkout the 'site' branch

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # Specify the path of your build directory if it's not the root

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
